WeChip/Models/Cliente.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WeChip.Models
{
    public class Cliente
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Nome é obrigatório")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Cpf é obrigatório")]
        public string Cpf { get; set; }
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Credito { get; set; }
        [NotMapped]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18,2)")]
        [Display(Name = "Crédito")]
        public string CreditoString { get; set; }
        [Required(ErrorMessage = "Telefone é obrigatório")]
        public string Telefone { get; set; }
        public Status Status { get; set; }
    }
}

WeChip/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using WeChip.Data;
using WeChip.Models;

namespace WeChip.Controllers
{
    public class ClientesController : Controller
    {
        private readonly WeChipDataBaseContext _context;

        public ClientesController(WeChipDataBaseContext context)
        {
            _context = context;
        }

        // GET: Cliestes
        public async Task<IActionResult> Index(string filtro)
        {
            if (TempData.Keys.Contains("Message"))
                ViewBag.Message = TempData["Message"];

            var clientes = from c in _context.Cliente
                           where c.Status.FinalizaCliente == false
                           select c;

            if (!String.IsNullOrEmpty(filtro))
            {
                filtro = filtro.Replace(".", "").Replace("-", "");
                clientes = clientes.Where(c => c.Nome.Contains(filtro) || c.Cpf.Contains(filtro));
            }

            return View(await clientes.Include(c => c.Status).Take(20).ToListAsync());
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            if (TempData.Keys.Contains("Message"))
                ViewBag.Message = TempData["Message"];
            
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome,Cpf,CreditoString,Telefone")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                cliente.Cpf = cliente.Cpf.Replace(".", "").Replace("-", "");
                cliente.Credito = Convert.ToDecimal(cliente.CreditoString);
                cliente.Status = _context.Status.Where(s => s.Descricao == "Nome Disponível").FirstOrDefault();
                
                _context.Add(cliente);
                await _context.SaveChangesAsync();

                TempData["Message"] = "Cliente salvo com sucesso!";
                return RedirectToAction(nameof(Index));
            }
            TempData["Message"] = "Ocorreu um erro inesperado. Tente novamente mais tarde.";
            return View(cliente);
        }
    }
}

WeChip/Controllers/OfertasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WeChip.Data;
using WeChip.Models;

namespace WeChip.Controllers
{
    public class OfertasController : Controller
    {
        private readonly WeChipDataBaseContext _context;

        public OfertasController(WeChipDataBaseContext context)
        {
            _context = context;
        }

        // GET: Ofertas/Create
        public IActionResult Create(int id)
        {
            if (TempData.Keys.Contains("Message"))
            {
                ViewBag.Message = TempData["Message"];
                ViewBag.Class = TempData["Class"];
            }

            ViewBag.Cliente = _context.Cliente.Include(c => c.Status).FirstOrDefault(c => c.ID == id);

            ViewBag.Produtos = new SelectList(
                _context.Produto.Select(p => 
                    new
                    {
                        p.CodigoProduto,
                        Descricao = "Descrição: " + p.Descricao + " | Preço: R$" + p.Preco + " | Tipo: " + p.Tipo.ToString()
                    })
                .ToList(), "CodigoProduto", "Descricao");

            ViewBag.Status = new SelectList(_context.Status
                .Where(s => s.Descricao != "Nome Disponível") // Forçar trocar o status inicial
                .ToList(), "CodigoStatus", "Descricao");

            return View();
        }

        // POST: Ofertas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Cliente,Cep,Rua,Numero,Complemento,Bairro,Cidade,Estado")] Oferta oferta, [Bind("CodigoStatus")] Status status, int[] produtos)
        {
            if (ModelState.IsValid)
            {
                oferta.Cliente.Credito = Convert.ToDecimal(oferta.Cliente.CreditoString);
                status = _context.Status.FirstOrDefault(s => s.CodigoStatus == status.CodigoStatus);
                if (produtos.Length > 0)
                {
                    oferta.OfertaProdutos = new List<OfertaProdutos>();
                    var totalProd = 0.0M;
                    // Obter os produtos enviados no post e somar os valores
                    foreach (int item in produtos)
                    {
                        var produto = _context.Produto.FirstOrDefault(p => p.CodigoProduto == item);
                        // Adicionar a lista de produtos e oferta para a OfertaProdutos
                        oferta.OfertaProdutos.Add(
                            new OfertaProdutos(){
                                Produto = produto,
                                Oferta = oferta
                            }
                        );
                        totalProd += produto.Preco;
                    }

                    var credito = Convert.ToDecimal(oferta.Cliente.Credito);
                    // Verificar se o cliente tem crédito para essa oferta de produtos
                    if (credito < totalProd)
                    {
                        TempData["Message"] = "Crédito insuficiente.";
                        TempData["Class"] = "danger";
                        return RedirectToAction("Create", new { id = oferta.Cliente.ID });
                    }

                    // Contendo produto(s) do tipo Hardware o endereço precisa ser preenchido
                    if ((oferta.OfertaProdutos.Where(p => p.Produto.Tipo == 0).FirstOrDefault() != null) && (string.IsNullOrEmpty(oferta.Cep) || 
                        string.IsNullOrEmpty(oferta.Rua) || 
                        string.IsNullOrEmpty(oferta.Bairro) || 
                        string.IsNullOrEmpty(oferta.Cidade) || 
                       string.IsNullOrEmpty(oferta.Estado) || 
                       oferta.Numero == null))
                    {
                        TempData["Message"] = "Preencha os campos de endereço.";
                        TempData["Class"] = "danger";
                        return RedirectToAction("Create", new { id = oferta.Cliente.ID });
                    }

                    // Oferta realizada com sucesso Cliente.Status.ContabilizaVenda deve ser verdadeiro 
                    oferta.Cliente.Status = status.ContabilizaVenda != true ? _context.Status.First(s => s.ContabilizaVenda == true) : status;

                    // Subtrair o crédito do cliente
                    oferta.Cliente.Credito = credito - totalProd;
                    // Contabiliza o valor Total da oferta
                    oferta.ValorTotal = totalProd;

                }
                else
                {
                    // Sem produto a venda não é contabilizada
                    oferta.Cliente.Status = status.ContabilizaVenda != false ? 
                        _context.Status.First(s => s.ContabilizaVenda == false && s.FinalizaCliente == false) : status;
                }

                _context.Entry(oferta.Cliente).State = EntityState.Modified;
                _context.Add(oferta);
                
                await _context.SaveChangesAsync();

                TempData["Message"] = "Oferta salva com sucesso!";
                TempData["Class"] = "success";
                return RedirectToAction("Index", "Clientes");
            }
            return View(oferta);
        }
    }
}

WeChip/Views/Clientes/Create.cshtml
@model WeChip.Models.Cliente

@{
    ViewData["Title"] = "Create";
}
<h4>Cadastro de cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cpf" class="control-label"></label>
                <input asp-for="Cpf" class="form-control cpf" />
                <span asp-validation-for="Cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreditoString" class="control-label"></label>
                <input asp-for="CreditoString" class="form-control money" value="0,00" />
                <span asp-validation-for="CreditoString" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control phone" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-gray-dark" />
                <a asp-action="Index" class="btn btn-danger">Cancelar</a>
            </div>
        </form>
    </div>
</div>
@if (ViewBag.Message != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.Message
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WeChip/Views/Clientes/Index.cshtml
@model IEnumerable<WeChip.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}
<div class="float-right">
    <a asp-action="Create" class="btn btn-gray-dark">Cadastrar cliente</a>
</div>
<form asp-controller="Clientes" asp-action="Index">
    <div class="row">
        <div class="col-4 pr-1">
            <input type="text" name="filtro" id="filtro" class="form-control mb-2 mr-sm-2 search" placeholder="Pesquisar cliente" />
        </div>
        <div class="col-8 pl-1">
            <button class="btn btn-gray-dark mb-2" id="pesquisar">Pesquisar</button>
        </div>
    </div>
</form>
<h5 class="text-center mb-3 mt-3">Lista de clientes</h5>
<table class="table table-hover text-center">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Credito)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Any())
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td class="cpf">
                        @Html.DisplayFor(modelItem => item.Cpf)
                    </td>
                    <td class="money2">
                        @Html.DisplayFor(modelItem => item.Credito)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Telefone)
                    </td>
                    <td>
                        <a asp-action="Create" asp-controller="Ofertas" asp-route-id="@item.ID" class="btn btn-secondary">Ofertar</a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="5">Nenhum cliente encontrado.</td>
            </tr>
        }
    </tbody>
</table>
@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}